// Code generated by mockery v1.0.0. DO NOT EDIT.

package persistence

import io "io"
import mock "github.com/stretchr/testify/mock"

// MockGetterSetter is an autogenerated mock type for the GetterSetter type
type MockMetadataStorer struct {
	mock.Mock
}

// GetMetadata provides a mock function with given fields: key, output
func (_m *MockMetadataStorer) GetMetadata(key io.Reader, output interface{}) error {
	ret := _m.Called(key, output)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, interface{}) error); ok {
		r0 = rf(key, output)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetMetadata provides a mock function with given fields: key, value
func (_m *MockMetadataStorer) SetMetadata(key io.Reader, value interface{}) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
