// Code generated by mockery v1.0.0. DO NOT EDIT.

package metadata

import io "io"
import mock "github.com/stretchr/testify/mock"

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

// ReadAllMetadata provides a mock function with given fields: key, into
func (_m *MockStorer) ReadAllMetadata(key io.Reader, into interface{}) error {
	ret := _m.Called(key, into)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, interface{}) error); ok {
		r0 = rf(key, into)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreMetadata provides a mock function with given fields: key, value
func (_m *MockStorer) StoreMetadata(key io.Reader, value interface{}) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
