workspace:
  base: /go/src
  path: github.com/endiangroup/specstack

clone:
  git:
    image: plugins/git:next
    pull: true
    tags: true

pipeline:
  vendor:
    image: endian/go:1.0.1
    commands:
      - dep ensure --vendor-only
    when:
      event: [pull_request]

  test:
    image: endian/go:1.0.1
    commands:
      - make lint test
    when:
      event: [pull_request]

  notify_dev:
    group: notify
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: specstack
    username: drone
    template: >
        *CI build #{{build.number}}* ({{build.event}} to `{{build.branch}}`{{#if build.pull}} [PR #{{build.pull}}]{{/if}} by @{{build.author}}) *{{#success build.status}}successful{{else}}failed{{/success}}* after {{since build.started}}
        _${DRONE_COMMIT_MESSAGE}_
        {{#if build.tag}}`v{{build.tag}}` | {{/if}}Commit <${DRONE_COMMIT_LINK}|{{build.commit}}> | <{{build.link}}|Build #{{build.number}}>
    when:
      event: [tag, pull_request]
      status: failure
