// Code generated by mockery v1.0.0. DO NOT EDIT.

package specstack

import mock "github.com/stretchr/testify/mock"

// MockSpecStack is an autogenerated mock type for the SpecStack type
type MockSpecStack struct {
	mock.Mock
}

// GetConfiguration provides a mock function with given fields: _a0
func (_m *MockSpecStack) GetConfiguration(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Initialise provides a mock function with given fields:
func (_m *MockSpecStack) Initialise() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListConfiguration provides a mock function with given fields:
func (_m *MockSpecStack) ListConfiguration() (map[string]string, error) {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
