// Code generated by mockery v1.0.0. DO NOT EDIT.

package specification

import mock "github.com/stretchr/testify/mock"

// MockSourcer is an autogenerated mock type for the Sourcer type
type MockSourcer struct {
	mock.Mock
}

// Source provides a mock function with given fields:
func (_m *MockSourcer) Source() Source {
	ret := _m.Called()

	var r0 Source
	if rf, ok := ret.Get(0).(func() Source); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Source)
	}

	return r0
}
